services:
  db:
    image: mysql:8.0
    container_name: elbuengusto_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: elbuengusto
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    command: --lower_case_table_names=1
volumes:
  mysql_data:
